project:
  type: website
  output-dir: docs

website:
  title: "Lauren Glevanik"
  navbar:
    left:
      - href: index.qmd
      - research.qmd
      - teaching.qmd
      - cv.qmd
      - commsci.qmd
      - photography.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

