project:
  type: website
  output-dir: docs
 
website:
  title: "Lauren Glevanik"
  site-url: https://lglevanik.github.io/
  navbar:
    left:
      - href: index.qmd
        text: " "
      - research.qmd
      - teaching.qmd
      - cv.qmd
      - commsci.qmd
      - photography.qmd
  page-footer:
    center: 'Built with <a href="https://www.r-project.org/" target="_blank">
              <img src="https://www.r-project.org/logo/Rlogo.png" width="20px" style="vertical-align: middle;">
           </a> and <a href="https://quarto.org/">Quarto</a>'

format:
  html:
    theme: cosmo
    include-in-header:
      - text: <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    css: styles.css
    toc: true
    page-layout: full

editor: visual

# git clone https://github.com/lglevanik/laurenglevanik.github.io.git
# cd laurenglevanik.github.io
# ls
# git remote show origin